#!/bin/bash

# Set the Orion OS version! 
# I hope you enjoy it! <3
# This script is part of the Orion OS project! <3


echo "Wold you like to continue with the installation of Orion OS 1.0? (y, n)"


read option

if [ $option == "y" ]; then
    echo "Ok! Let's continue!"
    echo "Setting the Orion OS version..."
    
    cat << "EOF"
     ~+

                 *       +
           '                  |
       ()    .-.,="``"=.    - o -
             '=/_       \     |
          *   |  '=._    |
               \     `=./`,        '
            .   '=.__.=' `='      *
   +                         +
        O      *        '       .
                 .
EOF
echo "Install git..."

sudo pacman -S git --noconfirm

echo "Install yay..."
git clone https://aur.archlinux.org/yay.git

cd yay

makepkg -si --noconfirm

cd ..

echo "Install hyprland..."

yay -S hyprland-git --noconfirm

echo "Install Astal..."

yay -S libastal-git --noconfirm

git clone https://github.com/aylur/astal.git
cd astal/core

sudo pacman -Syu meson vala gtk3 gtk-layer-shell gobject-introspection --nocofirm

meson setup build
meson install -C build

elif [ $option == "n" ]; then
    echo "Ok! Goodbye!"
    exit
else
    echo "Invalid option!"
fi

